version: "3.1"

services:
  db:
    container_name: postgresql_db
    image: postgres
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment: 
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: spring_db
    ports:
      - "5432:5432"
    networks:
      spring_net:
        ipv4_address: 172.16.0.2
  
  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment: 
      PGADMIN_DEFAULT_EMAIL : root@root.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    networks:
      spring_net:
        ipv4_address: 172.16.0.3

networks:
  spring_net:
    ipam:
      driver: default
      config:
        - subnet: "172.16.0.0/24"
